language: node_js
node_js:
- 'lts/*'
env:
  global:
  - GH_REF: github.com/tdukart/hue-colors.git
  - secure: MgfNGVAfsBNGYuZ30C7Zyu97iEgfOCq5qopa+rcUDb6a8CUQemnMZf6Fv+INyzFLXZmoV6usUyHR/PlugG1hPSH/JOJhhlLiJ+3MZ+/ZuzhMbesYhV0kpLtHENcMQPEOlonNAqu58EPK/E6PSLVlXCQa5HlTFRux2aJFzh51itigWhn/Hl4eqf4pFdW2pYSG0zIfPzlgNC7qamxTKz/1LxgxTdG792vZAEBPgWmUlNPo39z/HoIpKM4xz6Oce0ed8oM5G2IWdp089PGqjXrlbYw3Tn3BDLeUNa0zQryPriSjeVPd+0qSpE5Sf64qacpD2o+17Xny6mHReD9HW7vtKaWA17jr/T9Y2NDaZwrHwRvJheDaG7svRhjiTZcr1y5P2FEk5FmZZSJ0YE7FNlJLxfa8L4dEK70uWBNPPAIHGXf4xZkaah9yUt/SWjA03odM6lb+Au1ixTs2ySVfbHKN2Vwqnj/95HsnY5J3peNMN2RsvQYqWst9INllmd49p+lvYe6Q0KXgsd/juKKdUb0Ee6l2cr9JxO42EhaC7s+FzPceVVMKigdrmhQNoAJ90bEMkyI6cvSH2TZe/12Tm0ysu6D0uOVLgEK/2tjaTW0of0I1NB+2xGk/hYXyMJ5r2gg4Nk5xaAqiTKY4GRVNn8i3iGp8c3lkFmeEQeXEmJ5CGTo=
deploy:
- provider: releases
  api_key:
    secure: n5wZvXZ5dG2RqBJDW3IVOdqL8o7MNYdFdZhTzO+4MZ9B/T56YUFdqDxljitFmUCXqb6amQhFhSDMh47MKdH3kXk9xNIyEoEAdj+p9y5dCCS2tXI/huW+qSz98tQPOdJp93PvHvbJTdcC4FMTaR8wb+oDfRWewmRZd0yQtsWGANxdfxrzM3im/RWKSBvUSQTahCl2JSA+NNHHO4bDwPhPaoJxeruiB9D3Tb1362cm4md1jEzaa/9xym8XJ6ZmGhbtealzs9DoDeES+c0GcX6gA3L43HTKhA6dGzAOIABK3x+UV4juHuTjS6hRemg4tNbEKscrlzEiiUBSRPiGh2vvnJUpVVaQHB2No1IjVH+UCpmfvITrSFxWgauVFF747rgFSRNvpYCOgPwBhwVjwI/JSKFiHOrr5kXrNE072SeJ4rRkKxIqwKCnE+u+9pd6v0DlwqAPGqlqdqJymnWd6zcFiKror10Xi0QNzIs2NgPW+O+XlkjFaHKhLErfxW7l6bp/6ZjSoDuKexVwyxtgDIeiB4vs09zY7kFKr+HUBhB4xJV65VthAq2rl+/Z9y1cI6tKYNh3Nyu2gcQYVYgLLhkZsi4n2ItvGly1HHdkYsPfV3+/Lvs5S5ki2GVtihGkAmhcIKggnC10TXokCOmIDSCRkTGGXO1ga3MbhMPNKcltL8k=
  file: dist/index.js
  skip_cleanup: true
  on:
    repo: tdukart/hue-colors
    tags: true
- provider: npm
  email: tdukart@aloftinteractive.com
  api_key:
    secure: uYnNO9XFPQjeshDS8Il4vT0Sg+caD/Lzu5YDYURLKY3gL64NZTH1NY2PQ5u6vIC9yURQq/iALudy0W5xjUxvOGRKTGdze/HF32SbTliCinT6cymobj6Htxnw6bKbjP7ZSpispNBn0EoDgsnVct/DTxAdo5LhTCok1o9cG7LFMGk17Lgl74tA2dSgQ5aiVWDQ4bLR6jUGmyNE1uDkle91m8+/wNTmRlJtJgwH4cljlzdspMdJDEzqZ4FfovZGcjo6ZUiv6f+Riu2gBK7E6RCbfiMzytUMs4PXwuEQY3Dp7CWL/Por6wxsfTU5C5iGbmdo6vJgCLhEMYvLar0c/C7BZmqDvOwCbmjR1udi9cenKIC0WWSYS110RVXKI7ND2HEGtGPuZ8H92t5KAVkWNaFbC0PBdaCirHuP31ZSlizm4QcivlYaL8LoJ7zyjgsw6iw2I1tO2An3sNkEcFhs+3okro+A2msjkBEvFH99uxlmZtD/+J2X+FyMjKGrnBZVJPRlHx4rIAXYpkywAPw4/poioMe4LPHlUPtnbJGapKpzcS3gaMHjR3Q9MbmUQifNQGL2v3cS99CDFF8FQFwWK0nNUQhMdSSVXEtJGYjVIPJqlSRromBJ/aZKtXtmijAU2IR5J0JmHObFevJSKIq7FSudjksoQDrUmU5F3NILwB26ylQ=
  on:
    tags: true
    repo: tdukart/hue-colors
